### ISSUE TITLE
Team members-Ruby Capstone

### ISSUE THREAD

**Issue by RileyManda** [RileyManda/ruby-capstone-project#6]
We are a team of 3 members on this project: @rabayarabu | @DianaBeki & @RileyManda : And have completed setting up our Kanban board:🌱 

[Kanban project Link](https://github.com/RileyManda/ruby-capstone-project/projects/1)

Please kindly review our kanban board project setup and suggest improvements and changes if required.

Thank you 🙏🏻

**Comment by iambenkis** [comment]
#### Hi Team

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️  All cards has an assignee

## Suggested changes

- [ ] Each  card on the board should have the number of points in the \[Xpt\] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work. Kindly update that 👍 

![Capture](https://github.com/RileyManda/ruby-capstone-project/assets/80458199/8c069a91-6c6a-49eb-b29e-9df88231f64f)

![Capture](https://github.com/RileyManda/ruby-capstone-project/assets/80458199/47e21a7f-5e35-4a39-b282-6020faf4ebcd)

![Capture](https://github.com/RileyManda/ruby-capstone-project/assets/80458199/6b539a1c-a50b-412e-bfaf-36a3884554a3)


_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by roshan-bajgain** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- All cards is assign equally ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
